services:
  backend:
    build:
      context: ./backend
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_JWKS_URL=${COGNITO_JWKS_URL}
      - APP_BASE_URL=${APP_BASE_URL}
      - APP_CORS_ALLOWED_ORIGINS=${APP_CORS_ALLOWED_ORIGINS}
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE: ${VITE_API_BASE}
        VITE_COGNITO_USER_POOL_ID: ${VITE_COGNITO_USER_POOL_ID}
        VITE_COGNITO_CLIENT_ID: ${VITE_COGNITO_CLIENT_ID}
        VITE_COGNITO_REGION: ${VITE_COGNITO_REGION}
        VITE_BASE_URL: ${VITE_BASE_URL}
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE=${VITE_API_BASE}
      - VITE_COGNITO_USER_POOL_ID=${VITE_COGNITO_USER_POOL_ID}
      - VITE_COGNITO_CLIENT_ID=${VITE_COGNITO_CLIENT_ID}
      - VITE_COGNITO_REGION=${VITE_COGNITO_REGION}
      - VITE_BASE_URL=${VITE_BASE_URL}
